apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: drupal
  name: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
      name:  drupal
    spec:
      containers:
      - image: drupal:8.6
        name: init-sites-volumes
        command: [ "/bin/bash", "-c" ]
        args: [ 'cp -r /var/www/html/sites/ /data/; chown www-data:www-data /data/ -R' ]
        volumeMounts:
        - name: config
          mountPath: /data

      - image: drupal:8.6
        name: drupal

        volumeMounts:

        - name: config
          mountPath: /var/www/html/modules
          subPath: modules

        - name: config
          mountPath: /var/www/html/profiles
          subPath: profiles

        - name: config
          mountPath: /var/www/html/sites
          subPath: sites


        - name: config
          mountPath: /var/www/html/themes
          subPath: themes
          
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: drupal-pvc
