apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-service
spec:
  type: ClusterIP
  selector:
    app: redis
  clusterIP: None
  ports:
    - name: client
      port: 6379
    - name: gossip
      port: 16379
